name: Daily Commit

on:
  schedule:
    # Runs once every day at 09:00 UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # allows manual run

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add commit by 24f1002444@ds.study.iitm.ac.in
        run: |
          echo "Last updated on $(date)" > update.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "24f1002444@ds.study.iitm.ac.in"
          git add update.txt
          git commit -m "Automated daily commit"
          git push
